[mysql]
    [default]
        prefix = ''
        path = '127.0.0.1'
        port = '3306'
        user = 'root'
        pass = 'root'
        db = 'gin-template'
        config = 'charset=utf8mb4&parseTime=True&loc=Local'
        engine = 'InnoDB'
        singular = false
        logMode = 'error'
        maxIdleConns = 10
        maxOpenConns = 100
[hash-ids]
alphabet = 'FxnXM1kBN6cuhsAvjW3Co7l2RePyY8DwaU04Tzt9fHQrqSVKdpimLGIJOgb5ZE'

[project]
domain = '127.0.0.1'
local = 'zh-cn'
pidfile = '.pid'
port = 8087

[redis]
addr = '127.0.0.1:6379'
db = 1
mode = 'simple'
pass = 'bigdata'

[captcha]
keyLong = 6
imgWidth = 240
imgHeight = 80
openCaptcha = 0
openCaptchaTimeout = 1800