[project]
domain = "127.0.0.1"
port = 8087
local = "zh-cn"
pidfile = ".pid"
[database]
mode = "mysql"
[database.mysql]
isOpenReadDB = 1
[database.mysql.base]
connMaxLifeTime = 60
maxIdleConn = 60
maxOpenConn = 1
[database.mysql.read]
host = "127.0.0.1"
port = 3306
dataBase = "gin-template"
pass = "root"
user = "root"
[database.mysql.write]
host = "127.0.0.1"
port = 3306
dataBase = "gin-template"
pass = "root"
user = "root"
[database.postgresql]
isOpenReadDB = 1
[database.postgresql.base]
connMaxLifeTime = 60
maxIdleConn = 60
maxOpenConn = 1
[database.postgresql.read]
host = "127.0.0.1"
port = 5432
dataBase = "postgres"
pass = "qwer1234"
user = "postgres"
[database.postgresql.write]
host = "127.0.0.1"
port = 5432
dataBase = "postgres"
pass = "qwer1234"
user = "postgres"

[redis]
mode = "simple"
addr = "127.0.0.1:6379"
db = 1
pass = "bigdata"

[hash-ids]
alphabet = "FxnXM1kBN6cuhsAvjW3Co7l2RePyY8DwaU04Tzt9fHQrqSVKdpimLGIJOgb5ZE"